# Matlab Exercises

Try the exercises at [Quantitative Economics](www.http://quant-econ.net).

Some of the code for these exercises is in the `examples` folder in [my github repo][githubLH].

Some of my general purpose reusable code is posted in the `shared` folder in [my github repo][githubLH].

## Read the Matlab documentation on the following subjects:

* [Data types](www.mathworks.com/help/matlab/data-types_data-types.html): matrices, strings, structures.

* [Indexing](www.mathworks.com/.../matrix-indexing-in-matlab.html) to access matrix elements.

* [Operators](http://www.mathworks.com/help/matlab/operators-and-elementary-operations.html): `*,.*,/,./`

* [String handling](http://www.mathworks.com/help/matlab/ref/strings.html): [sprintf](www.mathworks.com/help/matlab/ref/sprintf.html)

* [Loops](http://www.mathworks.com/help/matlab/matlab_prog/loop-control-statements.html): while, for.

* [Functions](http://www.mathworks.com/help/matlab/function-basics.html): input/output arguments, global/local variables.

* [Optimization](www.mathworks.com/products/optimization): fzero, fsolve, optimset.

* [Graphics](www.mathworks.com/products/matlab/matlab-graphics): plot.

## Getting Started ##

1. Compute the mean and standard deviation for weighted data

	Input: data and weights (matrices)

	Output: mean and standard deviation for each column

	[My solution](https://github.com/hendri54/shared/blob/master/%2BstatsLH/std_w.m)
		
1. Compute the cdf for weighted data.

	Input: data and weights
	
	Output: cumulative percentiles and their values
	
	[My solution](https://github.com/hendri54/shared/blob/master/%2BdistribLH/cdf_weighted.m)
	
1. Compute points at the percentile distribution for weighted data (e.g. median)

	[My solution](https://github.com/hendri54/shared/blob/master/%2BdistribLH/pcnt_weighted.m)

## Root finding

Write a Matlab program that numerically finds the solution of 

\\( f\left(x,a\right) =x^{2}-a=0 \\) for \\(x\geq 0 \\)

* Write the deviation function \\( f(x) \\)

* Plot \\( f(x) \\) for \\( x \in [0,4] \\) .

* Find the solution for \\( a = 4 \\) using `fzero`.

* Find the solution for \\( a = 4 \\) using `fsolve`.

Try other algorithms, such as `fminsearch`  for fun.

## Growth Model ##

Consider a growth model given by the Bellman equation

\\(V(k) = \max u(c) + \beta V(f(k) - c) \\)

with \\(f(k) = k^\alpha\\).

Solve the growth model by value function iteration.

Steps:

1. Set up a grid for \\(k \\).
2. Start from an arbitrary guess \\( V_{0}(k) \\).
3. Iterate over the Bellman operator until \\( V \\) converges.

Along the way, plot the value functions to show how they converge to the true one. Like this:

![GrowthValueIter](figures/growth_value_iter.png "Value function iteration")

See [QuantEcon](http://quant-econ.net/jl/dp_intro.html) and my [Matlab solution](https://github.com/hendri54/Econ821/blob/master/matlab_examples/growth_model_821.m).

## Useful exercises from [QuantEcon](http://quant-econ.net)

1. Draw discrete random numbers

	Given: probability of each state

	[My solution](https://github.com/hendri54/shared/blob/master/%2BrandomLH/rand_discrete.m)

1. Simulate a Markov Chain

	See [QuantEcon](http://quant-econ.net/jl/finite_markov.html) for the setup and Julia code.

	Also compute the stationary distribution

	[My solution](https://github.com/hendri54/shared/blob/master/%2BmarkovLH/markov_sim.m)

	Also try their Exercise 1 (illustrate the central limit theorem).

2. [Approximate an AR1 with a Markov chain](http://quant-econ.net/jl/finite_markov.html#exercise-3) from QuantEcon.

	Do this at home by simply "translating" the Julia code into Matlab.

	You will see that the syntax is very similar.

	[My solution](https://github.com/hendri54/shared/blob/master/%2Bar1LH/tauchen.m)
		
2. Simulate random variables to illustrate the Law of Large Numbers and the Central Limit Theorem.

	See [QuantEcon](http://quant-econ.net/jl/lln_clt.html) for the setup and Julia code.
	
	[My solution](https://github.com/hendri54/Econ821/blob/master/matlab_examples/clt_illustrate_821.m)

------------------------

[githubLH]: https://github.com/hendri54
